stbSelecao.AppendLine("SELECT");
stbSelecao.AppendLine("    A.CONTA,");
stbSelecao.AppendLine("    D.CONTAC,");
stbSelecao.AppendLine("    D.DT_ABERT DATA_ABERT_CC,");
stbSelecao.AppendLine("    CASE");
stbSelecao.AppendLine("        WHEN D.ATIVO = 3 AND D.CONTAC IS NOT NULL THEN D.DT_ENCER -- só puxa as datas de encerramento de contas encerradas, evitando erros presentes no BD");
stbSelecao.AppendLine("        ELSE NULL");
stbSelecao.AppendLine("    END AS DATA_ENCER_CC,");
stbSelecao.AppendLine("    CASE");
stbSelecao.AppendLine("        WHEN D.ATIVO = 3 THEN 'Encerrada'");
stbSelecao.AppendLine("        WHEN D.CONTAC IS NULL THEN NULL");
stbSelecao.AppendLine("        ELSE 'Ativa'");
stbSelecao.AppendLine("    END AS SITUACAO_CC,");
stbSelecao.AppendLine("    A.NOME AS ASSOCIADO,");
stbSelecao.AppendLine("    A.CPF || A.CGC AS CPF_CNPJ,");
stbSelecao.AppendLine("    CASE");
stbSelecao.AppendLine("        WHEN A.FISICA LIKE 'F' THEN 'Física'");
stbSelecao.AppendLine("        WHEN A.FISICA LIKE 'J' THEN 'Jurídica'");
stbSelecao.AppendLine("    END AS PESSOA,");
stbSelecao.AppendLine("    CASE");
stbSelecao.AppendLine("        WHEN A.SITUACAO LIKE 'Normal' THEN 'Ativo'");
stbSelecao.AppendLine("        WHEN A.SITUACAO LIKE 'Inativo' THEN 'Inativo'");
stbSelecao.AppendLine("        WHEN A.SITUACAO LIKE 'Demissionário' THEN 'Encerrado'");
stbSelecao.AppendLine("        ELSE A.SITUACAO");
stbSelecao.AppendLine("    END AS SITUACAO_CADASTRO,");
stbSelecao.AppendLine("    A.DATACAD AS DATA_ABERT_CADASTRO,");
stbSelecao.AppendLine("    A.DEMISSAO AS DATA_ENCER_CADASTRO,");
stbSelecao.AppendLine("    AG.COD_AGENCIA UNID,");
stbSelecao.AppendLine("    AG.NOME UNIDADE,");
stbSelecao.AppendLine("    B.APELIDO AGENTE,");
stbSelecao.AppendLine("    CASE");
stbSelecao.AppendLine("        WHEN A.EXECUCAO = 'T' THEN 'S'");
stbSelecao.AppendLine("        WHEN A.EXECUCAO = 'F' THEN 'N'");
stbSelecao.AppendLine("        ELSE NULL");
stbSelecao.AppendLine("    END AS EM_EXECUCAO,");
stbSelecao.AppendLine("    A.DT_EXECUCAO DATA_EXECUCAO,");
stbSelecao.AppendLine("    CASE");
stbSelecao.AppendLine("        WHEN A.TEL1 IN ('--', '(  )    -    ') THEN NULL");
stbSelecao.AppendLine("        ELSE A.TEL1");
stbSelecao.AppendLine("    END AS TELEFONE,");
stbSelecao.AppendLine("    CASE");
stbSelecao.AppendLine("        WHEN A.TEL_WHATSAPP IN ('--', '(  )     -    ') THEN NULL");
stbSelecao.AppendLine("        ELSE A.TEL_WHATSAPP");
stbSelecao.AppendLine("    END AS TELEFONE_WHATSAPP,");
stbSelecao.AppendLine("    A.EMAIL");
stbSelecao.AppendLine("FROM");
stbSelecao.AppendLine("    FACMUTUO.C_CAD A");
stbSelecao.AppendLine("    INNER JOIN CC_AGENCIA AG ON A.COD_AGENCIA = AG.COD_AGENCIA");
stbSelecao.AppendLine("    LEFT JOIN FACMUTUO.C_CAD B ON A.AGENTE = B.CONTA");
stbSelecao.AppendLine("    LEFT JOIN FACMUTUO.CC_CADASSOC C ON A.CONTA = C.CONTA");
stbSelecao.AppendLine("    LEFT JOIN CC_CAD D ON C.CONTAC = D.CONTAC");
stbSelecao.AppendLine($"WHERE B.APELIDO LIKE '{pStrAgente}'");
stbSelecao.AppendLine("ORDER BY ASSOCIADO");

