SELECT * FROM F_CTCLOS A WHERE A.COD_LA = 17
UNION
SELECT * FROM F_CTOPEN B WHERE B.COD_LA = 17

--WHERE A.COD_LA = 17 OR B.COD_LA = 17
--SELECT * FROM SYS.COL WHERE CNAME LIKE 'COD_LA'

SELECT * FROM F_LA E --WHERE E.COD_LA = 17
SELECT * FROM F_IMPOSTOS F WHERE F.COD_LA = 17
SELECT UNIQUE(NOME) FROM F_CTOPEN WHERE NOME LIKE 'L%'