SELECT
    C.CONTA,
    C.NOME ASSOCIADO,
    C.ADM_COOP ADMISSAO,
    C.FISICA,
    C.CPF || C.CGC AS CPF_CNPJ,
    CC.CONTAC
FROM
    FACMUTUO.C_CAD C
    LEFT JOIN FACMUTUO.CC_CADASSOC CC_A ON C.CONTA = CC_A.CONTA AND CC_A.TITULAR = 'T'
    LEFT JOIN FACMUTUO.CC_CAD CC ON CC_A.CONTAC = CC.CONTAC
WHERE
    C.ASSOCIADO = 'T'
    AND C.DEMISSAO IS NULL
ORDER BY 
    C.NOME