SELECT
    C.NOME ASSOCIADO,
    COALESCE(C.CPF, C.CGC) CPF_CPNJ,
    C.CI RG,
    C.ORG_EXP,
    C.NACIONALIDADE,
    C.ENDERECO,
    C.END_NUM NUMERO,
    C.BAIRRO,
    D.NOME CIDADE,
    D.UF ESTADO,
    C.CEP
FROM
    FACMUTUO.C_CAD C
    LEFT JOIN FACMUTUO.C_CIDADE D ON C.COD_CID = D.COD_CID
WHERE
    C.ASSOCIADO = 'T'
    AND C.SITUACAO = 'Normal'
ORDER BY
    ASSOCIADO