SELECT
    A.CONTA,
    A.NOME,
    A.CPF,
    A.PPE,
    B.CARGO,
    B.PROFISSAO,
    A.ADM_COOP,
    PF2.COD_PERFIL,
    PF2.DESCRICAO
FROM
    C_CAD A
    LEFT JOIN C_CADUNI B ON A.CONTA = B.CONTA
    LEFT JOIN C_CAD_PERFIL PF1 ON A.CONTA = PF1.CONTA
    LEFT JOIN C_PERFIL PF2 ON PF1.COD_PERFIL = PF2.COD_PERFIL
WHERE
    A.PPE = 'T'
ORDER BY A.NOME