SELECT
    A.CONTA,
    C.CONTAC,
    A.CGC CNPJ,
    A.NOME ASSOCIADO,
    B.COD_ATIVIDADE,
    B.ATIVIDADE,
    PF2.COD_PERFIL,
    PF2.DESCRICAO
FROM
    FACMUTUO.C_CAD A
    LEFT JOIN FACMUTUO.C_ATIVIDADE B ON A.ATIVIDADE = B.COD_ATIVIDADE
    LEFT JOIN CC_CONTA C ON A.CONTA = C.CONTA
    LEFT JOIN CC_CADASSOC D ON A.CONTA = D.CONTA
    LEFT JOIN C_CAD_PERFIL PF1 ON A.CONTA = PF1.CONTA
    LEFT JOIN C_PERFIL PF2 ON PF1.COD_PERFIL = PF2.COD_PERFIL
WHERE
    A.CGC IS NOT NULL
    AND A.DEMISSAO IS NULL
    AND D.TITULAR = 'T'
ORDER BY
    A.NOME