SELECT
    DISTINCT A.NOME ASSOCIADO,
    A.EMAIL,
    A.TEL_CEL CELULAR,
    NVL(A.CPF, A.CGC) CPF,
    B.CONTAC,
    A.CONTA CADASTRO,
    A.FISICA,
    E.APELIDO AGENTE,
    A.COD_AGENCIA,
    C.COD_PACOTE,
    A.ENDERECO || ' nr ' || A.END_NUM ENDERECO,
    A.COMPL_END,
    TO_CHAR(A.ADM_COOP, 'dd/MM/yyyy') ADM_COOP,
    A.NACIONALIDADE,
    A.MATRICULA,
    A.EST_CIVIL,
    A.CI AS RG,
    F.PROFISSAO,
    G.NOME || '-' || G.UF CIDADE,
    A.CEP,
    H.NOME AS BAIRRO,
    C.LIMITE_CHESP,
    A.PAI,
    A.MAE,
    TO_CHAR(A.NASCIMENTO, 'dd/MM/yyyy') NASCIMENTO,
    A.NATURALIDADE,
    A.CONJUGUE,
    A.CPFCONJUGE,
    CASE
        WHEN D.NOME LIKE '%INDUSTRIAL%' THEN 'CASCAVEL'
        WHEN D.NOME LIKE '%CASCAVEL%' THEN 'CASCAVEL'
        ELSE D.NOME
    END UNIDADE
FROM
    FACMUTUO.C_CAD A,
    FACMUTUO.CC_CADASSOC B,
    FACMUTUO.CC_CAD C,
    FACMUTUO.CC_AGENCIA D,
    FACMUTUO.C_CAD E,
    FACMUTUO.C_CADUNI F,
    FACMUTUO.C_CIDADE G,
    FACMUTUO.C_BAIRRO H
WHERE
    A.CONTA = B.CONTA
    AND B.CONTA = F.CONTA(+)
    AND B.TITULAR = 'T'
    AND B.CONTAC = C.CONTAC
    AND C.ATIVO <> 3
    AND A.AGENTE = E.CONTA(+)
    AND A.COD_CID = G.COD_CID(+)
    AND A.COD_AGENCIA = D.COD_AGENCIA
    AND A.COD_BAI = H.COD_BAI
    AND A.SITUACAO = 'Normal'
    AND B.CONTA = F.CONTA
GROUP BY
    A.NOME,
    A.EMAIL,
    A.TEL_CEL,
    NVL(A.CPF, A.CGC),
    B.CONTAC,
    A.CONTA,
    A.FISICA,
    E.APELIDO,
    A.CEP,
    H.NOME,
    A.PAI,
    A.MAE,
    A.NASCIMENTO,
    A.NATURALIDADE,
    A.COMPL_END,
    A.COD_AGENCIA,
    C.COD_PACOTE,
    A.ENDERECO,
    A.ADM_COOP,
    A.NACIONALIDADE,
    A.EST_CIVIL,
    A.CI,
    F.PROFISSAO,
    D.NOME,
    G.UF,
    G.NOME,
    A.END_NUM,
    C.LIMITE_CHESP,
    A.MATRICULA,
    A.CONJUGUE,
    A.CPFCONJUGE
ORDER BY
    A.NOME