SELECT
    CONTAC,
    CONTA,
    DATA,
    NUM_CHEQUE,
    VALOR,
    LIMITE_CHESP,
    SALDO_ATUAL,
    DIAS_AD,
    SALDO_BLOQ,
    SUM(SALDO) AS EMPRESTIMO,
    NIVEL
FROM (
    SELECT
        (
            (
                FACMUTUO.FACCOR_FUNCTIONS.PEGASALDODIA(D.CONTAC, '21/08/2023')
                + FACMUTUO.FACCOR_FUNCTIONS.LIMITE_CHESP(D.CONTAC, '21/08/2023')
            )
        ) AS SALDO_ATUAL,
        B.CONTAC,
        D.CONTA,
        A.NUM_CHEQUE,
        A.VALOR,
        A.DT_ATUALIZADO AS DATA,
        C.LIMITE_CHESP,
        FACMUTUO.FACCOR_FUNCTIONS.NUMDIASAD(D.CONTAC, '21/08/2023') AS DIAS_AD,
        E.DESCRICAO AS NIVEL,
        FACMUTUO.FACCOR_FUNCTIONS.PEGASALDODIABLOQ(D.CONTAC, '21/08/2023') AS SALDO_BLOQ,
        F.SALDO
    FROM
        FACMUTUO.CC_CONTA D,
        FACMUTUO.CC_CHEQUE A,
        FACMUTUO.CC_TALAO B,
        FACMUTUO.CC_CAD C,
        FACMUTUO.E_NIVEL E,
        FACMUTUO.E_CTOPEN F
    WHERE
        A.COD_SITUACAO = 9
        --WHERE A.DEVOLUCAO = 2
        AND A.DT_ATUALIZADO LIKE '%21/08/2023%'
        AND A.COD_TALAO = B.COD_TALAO
        AND D.CONTAC = B.CONTAC
        AND B.CONTAC = C.CONTAC
        AND C.NV_ATUAL = E.NIVEL
        AND D.CONTA = F.CONTA(+)
    ORDER BY
        DT_ATUALIZADO DESC
)
GROUP BY
    CONTAC,
    CONTA,
    DATA,
    NUM_CHEQUE,
    VALOR,
    LIMITE_CHESP,
    SALDO_ATUAL,
    DIAS_AD,
    SALDO_BLOQ,
    NIVEL
