SELECT 
    G.SALDO AS VENCIDO,
    G.CONTA CONTA
FROM 
    FACMUTUO.CC_CONTA D
    JOIN FACMUTUO.E_CTOPEN G ON D.CONTA = G.CONTA
    JOIN FACMUTUO.CC_CHEQUE A ON A.DT_ATUALIZADO LIKE '%21/08/2023%'
    JOIN FACMUTUO.CC_TALAO B ON G.CONTAC = B.CONTAC AND B.COD_TALAO = A.COD_TALAO
WHERE 
    TO_DATE('21/08/2023') - G.VENC_FIM >= 1
    AND A.COD_SITUACAO = 9