SELECT
    COALESCE(A_SDA.CONTA, queryAplicacao.CONTA, VENCIDO.CONTA, C_CAD.CONTA) AS CONTA,
    C_CAD.NOME,
    C_CAD.COD_UNID,
    A_SDA.SD,
    queryAplicacao.APLICACAO,
    VENCIDO.VENCIDO
FROM FACMUTUO.A_SDA A_SDA
FULL OUTER JOIN (
    SELECT
        CONTA,
        SUM(VALOR) AS APLICACAO
    FROM F_CTOPEN
    WHERE NOME = 'Aplicação'
    GROUP BY CONTA
) queryAplicacao
ON A_SDA.CONTA = queryAplicacao.CONTA
FULL OUTER JOIN (
    SELECT
        G.SALDO AS VENCIDO,
        G.CONTA AS CONTA
    FROM
        FACMUTUO.CC_CONTA D
        JOIN FACMUTUO.E_CTOPEN G ON D.CONTA = G.CONTA
        JOIN FACMUTUO.CC_CHEQUE A ON A.DT_ATUALIZADO LIKE '%21/08/2023%'
        JOIN FACMUTUO.CC_TALAO B ON G.CONTAC = B.CONTAC AND B.COD_TALAO = A.COD_TALAO
    WHERE
        TO_DATE('21/08/2023') - G.VENC_FIM >= 1
        AND A.COD_SITUACAO = 9
) VENCIDO
ON A_SDA.CONTA = VENCIDO.CONTA
FULL OUTER JOIN C_CAD ON A_SDA.CONTA = C_CAD.CONTA
ORDER BY NOME