SELECT
    G.CONTAC,
    C.CONTA,
    C.MATRICULA,
    COALESCE(C.CPF, C.CGC) CPF_CPNJ,
    C.NOME,
    E.APELIDO AGENTE,
    C.COD_AGENCIA UNID,
    AG.NOME UNIDADE,
    PAC.COD_PACOTE,
    PAC.DESCRICAO PACOTE,
    CC.DT_ABERT DT_ABERT_CC,
    CASE
        WHEN C.NIVEL = 1 THEN 'AA'
        WHEN C.NIVEL = 2 THEN 'A'
        WHEN C.NIVEL = 3 THEN 'B'
        WHEN C.NIVEL = 4 THEN 'C'
        WHEN C.NIVEL = 5 THEN 'D'
        WHEN C.NIVEL = 6 THEN 'E'
        WHEN C.NIVEL = 7 THEN 'F'
        WHEN C.NIVEL = 8 THEN 'G'
        WHEN C.NIVEL = 9 THEN 'H'
    END AS NIVEL,
    C.ADM_COOP,
    C.SITUACAO,
    C.FISICA,
    CID.NOME CIDADE,
    -- C.DEMISSAO, --(SITUACAO NORMAL NAO VAI ESTAR DEMITIDO)
    -- C.MOTIVO_DEMISSAO,
    C.NASCIMENTO || ' (' || ANOSENTREDATAS(C.NASCIMENTO, SYSDATE) || ')' DT_NASC,
    CU.PROFISSAO,
    COALESCE(CU.SALARIO, (C.VRFATURAMENTO / 12)) SALARIO,
    Y.SD SALDO_CAPITAL,
    MV.VALOR SALARIO_CREDI
FROM
    C_CAD C
    LEFT JOIN FACMUTUO.CC_CADASSOC CC_A ON C.CONTA = CC_A.CONTA
    LEFT JOIN FACMUTUO.CC_CAD CC ON CC_A.CONTAC = CC.CONTAC
    LEFT JOIN C_CADUNI CU ON C.CONTA = CU.CONTA
    LEFT JOIN C_CIDADE CID ON C.COD_CID = CID.COD_CID
    LEFT JOIN C_UNID U ON C.COD_UNID = U.COD_UNID
    LEFT JOIN C_SETOR S ON C.COD_UNID = S.COD_UNID
    AND CU.COD_SET = S.COD_SET
    LEFT JOIN FACMUTUO.C_CAD E ON C.AGENTE = E.CONTA
    LEFT JOIN FACMUTUO.CC_AGENCIA AG ON C.COD_AGENCIA = AG.COD_AGENCIA
    LEFT JOIN FACMUTUO.CC_CONTA G ON CC_A.CONTAC = G.CONTAC
    LEFT JOIN FACMUTUO.CC_PACOTE PAC ON CC.COD_PACOTE = PAC.COD_PACOTE
    LEFT JOIN FACMUTUO.CC_MVCLOS MV ON CC.CONTAC = MV.CONTAC
    LEFT JOIN FACMUTUO.A_SDA Y ON C.CONTA = Y.CONTA
    INNER JOIN (
        SELECT
            CONTAC,
            MAX(DATA) AS MAX_DATA
        FROM
            CC_MVCLOS
        WHERE
            COD_LANC = 4015
            AND COMPENSADO = 'T'
        GROUP BY
            CONTAC
    ) maioresDatas ON MV.CONTAC = maioresDatas.CONTAC
    AND MV.DATA = maioresDatas.MAX_DATA
WHERE
    C.ASSOCIADO = 'T'
    AND C.SITUACAO = 'Normal'
    AND CC_A.TITULAR = 'T'
    AND Y.ANOMES > '2017/01'
    AND Y.ANOMES = (
        SELECT
            MAX(ANOMES)
        FROM
            A_SDA
    )
    AND MV.COD_LANC = 4015
    AND MV.COMPENSADO = 'T'
ORDER BY
    NOME --ADM_COOP DESC