SELECT
    DISTINCT C.CONTA,
    C.MATRICULA,
    COALESCE(C.CPF, C.CGC) CPF_CPNJ,
    G.CONTAC,
    C.NOME ASSOCIADO,
    CASE
        WHEN C.NIVEL = 1 THEN 'AA'
        WHEN C.NIVEL = 2 THEN 'A'
        WHEN C.NIVEL = 3 THEN 'B'
        WHEN C.NIVEL = 4 THEN 'C'
        WHEN C.NIVEL = 5 THEN 'D'
        WHEN C.NIVEL = 6 THEN 'E'
        WHEN C.NIVEL = 7 THEN 'F'
        WHEN C.NIVEL = 8 THEN 'G'
        WHEN C.NIVEL = 9 THEN 'H'
    END AS NIVEL,
    C.ADM_COOP ADMISSAO,
    CC.DT_ABERT DT_ABERT_CC,
    C.NASCIMENTO || ' (' || FACMUTUO.ANOSENTREDATAS(C.NASCIMENTO, SYSDATE) || ')' DT_NASC,
    CU.PROFISSAO,
    COALESCE(CU.SALARIO, (C.VRFATURAMENTO / 12)) SALARIO,
    querySD.SD SALDO_CAPITAL,
    C.COD_AGENCIA UNID,
    AG.NOME UNIDADE,
    E.APELIDO AGENTE,
    PAC.COD_PACOTE,
    PAC.DESCRICAO PACOTE,
    PF2.COD_PERFIL,
    PF2.DESCRICAO
FROM
    FACMUTUO.C_CAD C
    LEFT JOIN FACMUTUO.CC_CADASSOC CC_A ON C.CONTA = CC_A.CONTA
    LEFT JOIN FACMUTUO.CC_CAD CC ON CC_A.CONTAC = CC.CONTAC
    LEFT JOIN FACMUTUO.C_CADUNI CU ON C.CONTA = CU.CONTA
    LEFT JOIN FACMUTUO.C_CAD E ON C.AGENTE = E.CONTA
    LEFT JOIN FACMUTUO.CC_AGENCIA AG ON C.COD_AGENCIA = AG.COD_AGENCIA
    LEFT JOIN FACMUTUO.CC_CONTA G ON CC_A.CONTAC = G.CONTAC
    LEFT JOIN FACMUTUO.CC_PACOTE PAC ON CC.COD_PACOTE = PAC.COD_PACOTE
    LEFT JOIN (
        SELECT
            Y.CONTA,
            Y.ANOMES,
            Y.SD
        FROM
            FACMUTUO.A_SDA Y
            INNER JOIN (
                SELECT
                    CONTA,
                    MAX(ANOMES) ANOMES
                FROM
                    FACMUTUO.A_SDA
                GROUP BY
                    CONTA
            ) sdAnoMes ON Y.CONTA = sdAnoMes.CONTA
            AND Y.ANOMES = sdAnoMes.ANOMES
    ) querySD ON C.CONTA = querySD.CONTA
    LEFT JOIN FACMUTUO.CC_MVCLOS MV ON CC.CONTAC = MV.CONTAC
    LEFT JOIN (
        SELECT
            CONTAC,
            MAX(DATA) AS MAX_DATA
        FROM
            FACMUTUO.CC_MVCLOS
        WHERE
            COD_LANC = 4015
            AND COMPENSADO = 'T'
        GROUP BY
            CONTAC
    ) maioresDatas ON MV.CONTAC = maioresDatas.CONTAC
    AND MV.DATA = maioresDatas.MAX_DATA
    LEFT JOIN FACMUTUO.C_CAD_PERFIL PF1 ON C.CONTA = PF1.CONTA
    LEFT JOIN FACMUTUO.C_PERFIL PF2 ON PF1.COD_PERFIL = PF2.COD_PERFIL
WHERE
    CC_A.TITULAR = 'T'
    AND C.ASSOCIADO = 'T'
    AND C.SITUACAO = 'Normal'
ORDER BY
    ASSOCIADO --ADM_COOP DESC