SELECT
    C.CONTA,
    CC.CONTAC,
    CC.DT_ABERT DT_ABERT_CC
FROM
    FACMUTUO.C_CAD C
    LEFT JOIN FACMUTUO.CC_CADASSOC CC_A ON C.CONTA = CC_A.CONTA
    LEFT JOIN FACMUTUO.CC_CAD CC ON CC_A.CONTAC = CC.CONTAC
WHERE
    CC_A.TITULAR = 'T'
ORDER BY
    CONTA