SELECT
    COALESCE(queryAberto.CONTA, queryFechado.CONTA) CONTA,
    COALESCE(queryAberto.VALOR_ABERTO, 0) AS VALOR_ABERTO,
    COALESCE(queryFechado.VALOR_FECHADO, 0) AS VALOR_FECHADO,
    COALESCE(queryAberto.VALOR_ABERTO, 0) + COALESCE(queryFechado.VALOR_FECHADO, 0) AS VALOR_TOTAL
FROM (
    SELECT CONTA, SUM(VALOR) AS VALOR_ABERTO
    FROM A_MVOPEN
    WHERE COD_LANC = '202'
    GROUP BY CONTA
) queryAberto
FULL OUTER JOIN (
    SELECT CONTA, SUM(VALOR) AS VALOR_FECHADO
    FROM A_MVCLOS
    WHERE COD_LANC = '202'
    GROUP BY CONTA
) queryFechado
ON queryAberto.CONTA = queryFechado.CONTA
