(
    SELECT
        A.CONTA,
        COALESCE(Y.VRFATURAMENTO, Z.SALARIO) AS SALARIO_FATURAMENTO --PEGA O FATURAMENTO SE TIVER, CASO CONTRÁRIO PEGA O SALÁRIO EM CADASTROS QUE TENHAM AMBOS, SERÁ CONSIDERADO O FATURAMENTO (DA CONTA PJ ABERTA NA CREDI) 
    FROM
        C_CAD Y
        INNER JOIN C_CADUNI Z ON Y.CONTA = Z.CONTA
) querySalarioOuFaturamento