SELECT
    CASE
        WHEN A.STATUS = '6' THEN 'Inativa'
        ELSE 'Ativa'
    END AS SITUACAO,
    CASE
        WHEN A.STATUS = '1' THEN 'Incluída'
        WHEN A.STATUS = '2' THEN 'Marc. p/ Inclusão'
        WHEN A.STATUS = '3' THEN 'Marc. p/ Exclusão'
        WHEN A.STATUS = '4' THEN 'Em Inclusão'
        WHEN A.STATUS = '5' THEN 'Em Exclusão'
        WHEN A.STATUS = '6' THEN 'Excluída'
    END AS STATUS,
    A.CONTAC,
    A.CONTA CONTA_EMITENTE,
    D.NOME TITULAR,
    E.COD_AGENCIA UNID,
    E.NOME UNIDADE,
    A.INCLUSAO DT_INCLUSAO,
    A.NUM_CHEQUE CHEQUE,
    A.VALOR,
    C.MOTIVO
FROM
    FACMUTUO.CC_CCF A
    LEFT JOIN (SELECT COD_MOTDEV, (COD_MOTDEV || ' - ' || DESCRICAO) AS MOTIVO FROM FACMUTUO.CC_MOTDEV) C
    ON A.COD_MOTDEV = C.COD_MOTDEV
    LEFT JOIN (SELECT CONTA, NOME, COD_AGENCIA FROM FACMUTUO.C_CAD) D
    ON A.CONTA = D.CONTA
    LEFT JOIN FACMUTUO.CC_AGENCIA E
    ON D.COD_AGENCIA = E.COD_AGENCIA

