stbSelecao.AppendLine("SELECT");
stbSelecao.AppendLine("    G.CONTAC,");
stbSelecao.AppendLine("    C.CONTA,");
stbSelecao.AppendLine("    COALESCE(");
stbSelecao.AppendLine("        REPLACE(REPLACE(C.CPF, '.', ''), '-', ''),");
stbSelecao.AppendLine("        REPLACE(");
stbSelecao.AppendLine("            REPLACE(REPLACE(C.CGC, '.', ''), '-', ''),");
stbSelecao.AppendLine("            '/',");
stbSelecao.AppendLine("            ''");
stbSelecao.AppendLine("        )");
stbSelecao.AppendLine("    ) CPF_CNPJ,");
stbSelecao.AppendLine("    C.NOME,");
stbSelecao.AppendLine("    C.DEMISSAO,");
stbSelecao.AppendLine("    CASE");
stbSelecao.AppendLine("        C.NIVEL");
stbSelecao.AppendLine("        WHEN 1 THEN 'AA'");
stbSelecao.AppendLine("        WHEN 2 THEN 'A'");
stbSelecao.AppendLine("        WHEN 3 THEN 'B'");
stbSelecao.AppendLine("        WHEN 4 THEN 'C'");
stbSelecao.AppendLine("        WHEN 5 THEN 'D'");
stbSelecao.AppendLine("        WHEN 6 THEN 'E'");
stbSelecao.AppendLine("        WHEN 7 THEN 'F'");
stbSelecao.AppendLine("        WHEN 8 THEN 'G'");
stbSelecao.AppendLine("        WHEN 9 THEN 'H'");
stbSelecao.AppendLine("        ELSE ''");
stbSelecao.AppendLine("    END AS NIVEL,");
stbSelecao.AppendLine("    C.ADM_COOP,");
stbSelecao.AppendLine("    C.SITUACAO,");
stbSelecao.AppendLine("    C.FISICA,");
stbSelecao.AppendLine("    C.MOTIVO_DEMISSAO,");
stbSelecao.AppendLine("    C.NASCIMENTO DT_NASC,");
stbSelecao.AppendLine("    FACMUTUO.ANOSENTREDATAS(C.NASCIMENTO, SYSDATE) AS IDADE,");
stbSelecao.AppendLine("    CU.PROFISSAO,");
stbSelecao.AppendLine("    CU.SALARIO,");
stbSelecao.AppendLine("    C.VRFATURAMENTO FATURAMENTO,");
stbSelecao.AppendLine("    Y.SD SALDO_CAPITAL,");
stbSelecao.AppendLine("    K.VLR_LIMITE LIMITE,");
stbSelecao.AppendLine("    FACMUTUO.FACCOR_FUNCTIONS.LIMITE_CHESP(F.CONTAC, SYSDATE) AS LIM_CHESP,");
stbSelecao.AppendLine("    M.PATRIMONIO,");
stbSelecao.AppendLine("    N.CHDEV,");
stbSelecao.AppendLine("    P.DESCR_GRUPO,");
stbSelecao.AppendLine("    R.RISCO,");
stbSelecao.AppendLine("    T.DEBITO,");
stbSelecao.AppendLine("    T.CREDITO,");
stbSelecao.AppendLine("    C.CONJUGUE,");
stbSelecao.AppendLine("    C.CPFCONJUGE");
stbSelecao.AppendLine("FROM");
stbSelecao.AppendLine("    FACMUTUO.C_CAD C");
stbSelecao.AppendLine("    LEFT JOIN FACMUTUO.C_CADUNI CU ON CU.CONTA = C.CONTA");
stbSelecao.AppendLine("    LEFT JOIN FACMUTUO.CC_CADASSOC F ON C.CONTA = F.CONTA");
stbSelecao.AppendLine("    AND F.TITULAR = 'T'");
stbSelecao.AppendLine("    LEFT JOIN FACMUTUO.CC_CONTA G ON F.CONTAC = G.CONTAC");
stbSelecao.AppendLine("    LEFT JOIN FACMUTUO.E_ASSOC_GPSOL O ON C.CONTA = O.CONTA");
stbSelecao.AppendLine("    LEFT JOIN FACMUTUO.E_GPSOL P ON O.ID_GPSOL = P.ID_GPSOL");
stbSelecao.AppendLine("    LEFT JOIN FACMUTUO.A_SD Y ON C.CONTA = Y.CONTA");
stbSelecao.AppendLine("    LEFT JOIN (");
stbSelecao.AppendLine("        SELECT");
stbSelecao.AppendLine("            K.CONTAC,");
stbSelecao.AppendLine("            K.ATIVO,");
stbSelecao.AppendLine("            SUM(K.VLR_LIMITE) AS VLR_LIMITE");
stbSelecao.AppendLine("        FROM");
stbSelecao.AppendLine("            FACMUTUO.CC_CARTAO K");
stbSelecao.AppendLine("        WHERE");
stbSelecao.AppendLine("            (");
stbSelecao.AppendLine("                K.ATIVO = '1'");
stbSelecao.AppendLine("                OR K.ATIVO IS NULL");
stbSelecao.AppendLine("                OR K.ATIVO = '3'");
stbSelecao.AppendLine("            )");
stbSelecao.AppendLine("        GROUP BY");
stbSelecao.AppendLine("            K.CONTAC,");
stbSelecao.AppendLine("            K.ATIVO");
stbSelecao.AppendLine("    ) K ON F.CONTAC = K.CONTAC");
stbSelecao.AppendLine("    LEFT JOIN (");
stbSelecao.AppendLine("        SELECT");
stbSelecao.AppendLine("            CONTA,");
stbSelecao.AppendLine("            SUM(SOMA) AS PATRIMONIO");
stbSelecao.AppendLine("        FROM");
stbSelecao.AppendLine("            (");
stbSelecao.AppendLine("                SELECT");
stbSelecao.AppendLine("                    CONTA,");
stbSelecao.AppendLine("                    SUM(VALOR) SOMA,");
stbSelecao.AppendLine("                    'Imoveis Urbanos' Nome");
stbSelecao.AppendLine("                FROM");
stbSelecao.AppendLine("                    FACMUTUO.CR_IMOU");
stbSelecao.AppendLine("                GROUP BY");
stbSelecao.AppendLine("                    CONTA");
stbSelecao.AppendLine("                UNION");
stbSelecao.AppendLine("                ALL");
stbSelecao.AppendLine("                SELECT");
stbSelecao.AppendLine("                    CONTA,");
stbSelecao.AppendLine("                    SUM(VALOR) SOMA,");
stbSelecao.AppendLine("                    'Imoveis Rurais' Nome");
stbSelecao.AppendLine("                FROM");
stbSelecao.AppendLine("                    FACMUTUO.CR_IMOR");
stbSelecao.AppendLine("                GROUP BY");
stbSelecao.AppendLine("                    CONTA");
stbSelecao.AppendLine("                UNION");
stbSelecao.AppendLine("                ALL");
stbSelecao.AppendLine("                SELECT");
stbSelecao.AppendLine("                    CONTA,");
stbSelecao.AppendLine("                    SUM(VALOR) SOMA,");
stbSelecao.AppendLine("                    'Rebanho' Nome");
stbSelecao.AppendLine("                FROM");
stbSelecao.AppendLine("                    FACMUTUO.CR_REB");
stbSelecao.AppendLine("                GROUP BY");
stbSelecao.AppendLine("                    CONTA");
stbSelecao.AppendLine("                UNION");
stbSelecao.AppendLine("                ALL");
stbSelecao.AppendLine("                SELECT");
stbSelecao.AppendLine("                    CONTA,");
stbSelecao.AppendLine("                    SUM(VALOR) SOMA,");
stbSelecao.AppendLine("                    'Capital Fixo / Semi Fixo' Nome");
stbSelecao.AppendLine("                FROM");
stbSelecao.AppendLine("                    FACMUTUO.CR_CAP");
stbSelecao.AppendLine("                GROUP BY");
stbSelecao.AppendLine("                    CONTA");
stbSelecao.AppendLine("                UNION");
stbSelecao.AppendLine("                ALL");
stbSelecao.AppendLine("                SELECT");
stbSelecao.AppendLine("                    CONTA,");
stbSelecao.AppendLine("                    SUM(VALOR) SOMA,");
stbSelecao.AppendLine("                    'Responsabilidades' Nome");
stbSelecao.AppendLine("                FROM");
stbSelecao.AppendLine("                    FACMUTUO.CR_RESP");
stbSelecao.AppendLine("                GROUP BY");
stbSelecao.AppendLine("                    CONTA");
stbSelecao.AppendLine("                UNION");
stbSelecao.AppendLine("                ALL");
stbSelecao.AppendLine("                SELECT");
stbSelecao.AppendLine("                    CONTA,");
stbSelecao.AppendLine("                    SUM(VALOR) - SUM(VALOR_FIN) SOMA,");
stbSelecao.AppendLine("                    'Veículos' Nome");
stbSelecao.AppendLine("                FROM");
stbSelecao.AppendLine("                    FACMUTUO.CM_AUTO");
stbSelecao.AppendLine("                GROUP BY");
stbSelecao.AppendLine("                    CONTA");
stbSelecao.AppendLine("                UNION");
stbSelecao.AppendLine("                ALL");
stbSelecao.AppendLine("                SELECT");
stbSelecao.AppendLine("                    CONTA,");
stbSelecao.AppendLine("                    (");
stbSelecao.AppendLine("                        APLIC_FUNDO_INVEST + APLIC_DEP_PRAZO + APLIC_BOLSA_VALORES + APLIC_TIT_PUBLICO + OUTROS_VALOR");
stbSelecao.AppendLine("                    ) SOMA,");
stbSelecao.AppendLine("                    'Direitos/Outros' Nome");
stbSelecao.AppendLine("                FROM");
stbSelecao.AppendLine("                    FACMUTUO.C_DIREITOS");
stbSelecao.AppendLine("            )");
stbSelecao.AppendLine("        GROUP BY");
stbSelecao.AppendLine("            CONTA");
stbSelecao.AppendLine("    ) M ON C.CONTA = M.CONTA");
stbSelecao.AppendLine("    LEFT JOIN (");
stbSelecao.AppendLine("        SELECT");
stbSelecao.AppendLine("            E.CONTA,");
stbSelecao.AppendLine("            COUNT(*) AS CHDEV");
stbSelecao.AppendLine("        FROM");
stbSelecao.AppendLine("            FACMUTUO.CC_CHEQUEC A");
stbSelecao.AppendLine("            INNER JOIN FACMUTUO.CC_TALAO B ON A.COD_TALAO = B.COD_TALAO");
stbSelecao.AppendLine("            INNER JOIN FACMUTUO.CC_CADASSOC D ON D.CONTAC = B.CONTAC");
stbSelecao.AppendLine("            INNER JOIN FACMUTUO.C_CAD E ON E.CONTA = D.CONTA");
stbSelecao.AppendLine("        WHERE");
stbSelecao.AppendLine("            A.COD_SITUACAO = 9");
stbSelecao.AppendLine("            AND A.COD_MOTDEV IN(11, 12)");
stbSelecao.AppendLine($"            AND A.DATA BETWEEN '{pDataInicioSeisMeses}'");
stbSelecao.AppendLine($"            AND '{pDataFimSeisMeses}'");
stbSelecao.AppendLine("            AND TO_CHAR(D.TITULAR) = 'T'");
stbSelecao.AppendLine("        GROUP BY");
stbSelecao.AppendLine("            E.CONTA");
stbSelecao.AppendLine("    ) N ON C.CONTA = N.CONTA");
stbSelecao.AppendLine("    LEFT JOIN (");
stbSelecao.AppendLine("        SELECT");
stbSelecao.AppendLine("            DSGRUPO,");
stbSelecao.AppendLine("            CDGRUPO,");
stbSelecao.AppendLine("            SUM(SALDO_EMP + SALDO_CCH) AS RISCO");
stbSelecao.AppendLine("        FROM");
stbSelecao.AppendLine("            (");
stbSelecao.AppendLine("                SELECT");
stbSelecao.AppendLine("                    G.ID_GPSOL AS CDGRUPO,");
stbSelecao.AppendLine("                    G.DESCR_GRUPO AS DSGRUPO,");
stbSelecao.AppendLine("                    SUM(");
stbSelecao.AppendLine("                        FACMUTUO.EMPREST.PEGASOSALDO(1, GA.CONTA, SYSDATE)");
stbSelecao.AppendLine("                    ) AS SALDO_EMP,");
stbSelecao.AppendLine("                    SUM(NVL(CC.SALDO, 0)) AS SALDO_CCH");
stbSelecao.AppendLine("                FROM");
stbSelecao.AppendLine("                    FACMUTUO.E_GPSOL G");
stbSelecao.AppendLine("                    INNER JOIN FACMUTUO.E_ASSOC_GPSOL GA ON G.ID_GPSOL = GA.ID_GPSOL");
stbSelecao.AppendLine("                    INNER JOIN (");
stbSelecao.AppendLine("                        SELECT");
stbSelecao.AppendLine("                            DISTINCT CA.CONTA,");
stbSelecao.AppendLine("                            SUM(");
stbSelecao.AppendLine("                                FACMUTUO.FACCOR_FUNCTIONS.PEGASALDOAD(CA.CONTAC, SYSDATE) + FACMUTUO.FACCOR_FUNCTIONS.LIMITE_CHESP(CA.CONTAC, SYSDATE)");
stbSelecao.AppendLine("                            ) AS SALDO");
stbSelecao.AppendLine("                        FROM");
stbSelecao.AppendLine("                            FACMUTUO.CC_CADASSOC CA");
stbSelecao.AppendLine("                            LEFT JOIN FACMUTUO.E_ASSOC_GPSOL GP ON CA.CONTA = GP.CONTA");
stbSelecao.AppendLine("                            INNER JOIN (");
stbSelecao.AppendLine("                                SELECT");
stbSelecao.AppendLine("                                    GP.ID_GPSOL");
stbSelecao.AppendLine("                                FROM");
stbSelecao.AppendLine("                                    FACMUTUO.E_ASSOC_GPSOL GP");
stbSelecao.AppendLine("                                    LEFT JOIN FACMUTUO.C_CAD C ON GP.CONTA = C.CONTA");
stbSelecao.AppendLine("                                WHERE");
stbSelecao.AppendLine($"                                    C.CPF || C.CGC LIKE '{pDoc}'");
stbSelecao.AppendLine("                            ) F_GP ON GP.ID_GPSOL = F_GP.ID_GPSOL -- FILTRO POR DOCUMENTO NA SOMA PRA OTIMIZAR O TEMPO DE EXECUÇÃO");
stbSelecao.AppendLine("                            -- SOMA APENAS OS SALDOS DE QUEM PERTENCE AO GRUPO SOLIDARIO DA PESSOA COM O DOCUMENTO INFORMADO ACIMA");
stbSelecao.AppendLine("                        WHERE");
stbSelecao.AppendLine("                            CA.TITULAR = 'T'");
stbSelecao.AppendLine("                        GROUP BY");
stbSelecao.AppendLine("                            CA.CONTA");
stbSelecao.AppendLine("                    ) CC ON GA.CONTA = CC.CONTA");
stbSelecao.AppendLine("                GROUP BY");
stbSelecao.AppendLine("                    G.ID_GPSOL,");
stbSelecao.AppendLine("                    G.DESCR_GRUPO,");
stbSelecao.AppendLine("                    G.RESPONSAVEL");
stbSelecao.AppendLine("            )");
stbSelecao.AppendLine("        GROUP BY");
stbSelecao.AppendLine("            DSGRUPO,");
stbSelecao.AppendLine("            CDGRUPO");
stbSelecao.AppendLine("    ) R ON P.ID_GPSOL = R.CDGRUPO");
stbSelecao.AppendLine("    LEFT JOIN (");
stbSelecao.AppendLine("        SELECT");
stbSelecao.AppendLine("            CONTAC,");
stbSelecao.AppendLine("            SUM(CREDITO) AS CREDITO,");
stbSelecao.AppendLine("            SUM(DEBITO) AS DEBITO");
stbSelecao.AppendLine("        FROM");
stbSelecao.AppendLine("            (");
stbSelecao.AppendLine("                SELECT");
stbSelecao.AppendLine("                    MVO.CONTAC,");
stbSelecao.AppendLine("                    SUM(MVO.VALOR) AS CREDITO,");
stbSelecao.AppendLine("                    0 AS DEBITO");
stbSelecao.AppendLine("                FROM");
stbSelecao.AppendLine("                    FACMUTUO.CC_MVOPEN MVO");
stbSelecao.AppendLine($"                    INNER JOIN FACMUTUO.CC_CADASSOC CC_A ON MVO.CONTAC = CC_A.CONTAC AND CC_A.CONTAC LIKE '{pCC}'");
stbSelecao.AppendLine($"                    INNER JOIN FACMUTUO.C_CAD C ON CC_A.CONTA = C.CONTA AND C.CPF || C.CGC LIKE '{pDoc}'");
stbSelecao.AppendLine("                WHERE");
stbSelecao.AppendLine($"                    MVO.DATA BETWEEN '{pDataIniTresMeses}'");
stbSelecao.AppendLine($"                    AND '{pDataFimTresMeses}'");
stbSelecao.AppendLine("                    AND MVO.DC = 'C'");
stbSelecao.AppendLine("                GROUP BY");
stbSelecao.AppendLine("                    MVO.CONTAC");
stbSelecao.AppendLine("                UNION");
stbSelecao.AppendLine("                ALL");
stbSelecao.AppendLine("                SELECT");
stbSelecao.AppendLine("                    MVC.CONTAC,");
stbSelecao.AppendLine("                    SUM(MVC.VALOR) AS CREDITO,");
stbSelecao.AppendLine("                    0 AS DEBITO");
stbSelecao.AppendLine("                FROM");
stbSelecao.AppendLine("                    FACMUTUO.CC_MVCLOS MVC");
stbSelecao.AppendLine($"                    INNER JOIN FACMUTUO.CC_CADASSOC CC_A ON MVC.CONTAC = CC_A.CONTAC AND CC_A.CONTAC LIKE '{pCC}'");
stbSelecao.AppendLine($"                    INNER JOIN FACMUTUO.C_CAD C ON CC_A.CONTA = C.CONTA AND C.CPF || C.CGC LIKE '{pDoc}'");
stbSelecao.AppendLine("                WHERE");
stbSelecao.AppendLine($"                    MVC.DATA BETWEEN '{pDataIniTresMeses}'");
stbSelecao.AppendLine($"                    AND '{pDataFimTresMeses}'");
stbSelecao.AppendLine("                    AND MVC.DC = 'C'");
stbSelecao.AppendLine("                GROUP BY");
stbSelecao.AppendLine("                    MVC.CONTAC");
stbSelecao.AppendLine("                UNION");
stbSelecao.AppendLine("                ALL");
stbSelecao.AppendLine("                SELECT");
stbSelecao.AppendLine("                    MVO.CONTAC,");
stbSelecao.AppendLine("                    0 AS CREDITO,");
stbSelecao.AppendLine("                    SUM(MVO.VALOR) AS DEBITO");
stbSelecao.AppendLine("                FROM");
stbSelecao.AppendLine("                    FACMUTUO.CC_MVOPEN MVO");
stbSelecao.AppendLine($"                    INNER JOIN FACMUTUO.CC_CADASSOC CC_A ON MVO.CONTAC = CC_A.CONTAC AND CC_A.CONTAC LIKE '{pCC}'");
stbSelecao.AppendLine($"                    INNER JOIN FACMUTUO.C_CAD C ON CC_A.CONTA = C.CONTA AND C.CPF || C.CGC LIKE '{pDoc}'");
stbSelecao.AppendLine("                WHERE");
stbSelecao.AppendLine($"                    MVO.DATA BETWEEN '{pDataIniTresMeses}'");
stbSelecao.AppendLine($"                    AND '{pDataFimTresMeses}'");
stbSelecao.AppendLine("                    AND MVO.DC = 'D'");
stbSelecao.AppendLine("                GROUP BY");
stbSelecao.AppendLine("                    MVO.CONTAC");
stbSelecao.AppendLine("                UNION");
stbSelecao.AppendLine("                ALL");
stbSelecao.AppendLine("                SELECT");
stbSelecao.AppendLine("                    MVC.CONTAC,");
stbSelecao.AppendLine("                    0 AS CREDITO,");
stbSelecao.AppendLine("                    SUM(MVC.VALOR) AS DEBITO");
stbSelecao.AppendLine("                FROM");
stbSelecao.AppendLine("                    FACMUTUO.CC_MVCLOS MVC");
stbSelecao.AppendLine($"                    INNER JOIN FACMUTUO.CC_CADASSOC CC_A ON MVC.CONTAC = CC_A.CONTAC AND CC_A.CONTAC LIKE '{pCC}'");
stbSelecao.AppendLine($"                    INNER JOIN FACMUTUO.C_CAD C ON CC_A.CONTA = C.CONTA AND C.CPF || C.CGC LIKE '{pDoc}'");
stbSelecao.AppendLine("                WHERE");
stbSelecao.AppendLine($"                    MVC.DATA BETWEEN '{pDataIniTresMeses}'");
stbSelecao.AppendLine($"                    AND '{pDataFimTresMeses}'");
stbSelecao.AppendLine("                    AND MVC.DC = 'D'");
stbSelecao.AppendLine("                GROUP BY");
stbSelecao.AppendLine("                    MVC.CONTAC");
stbSelecao.AppendLine("            )");
stbSelecao.AppendLine("        GROUP BY");
stbSelecao.AppendLine("            CONTAC");
stbSelecao.AppendLine("    ) T ON F.CONTAC = T.CONTAC");
stbSelecao.AppendLine("WHERE");
stbSelecao.AppendLine("    C.ASSOCIADO = 'T'");
stbSelecao.AppendLine("    AND C.SITUACAO = 'Normal'");
stbSelecao.AppendLine($"    AND C.CPF || C.CGC LIKE '{pDoc}'");
stbSelecao.AppendLine($"    AND G.CONTAC LIKE '{pCC}'");
stbSelecao.AppendLine("ORDER BY");
stbSelecao.AppendLine("    C.NOME");