stbSelecao.AppendLine("SELECT");
stbSelecao.AppendLine("DISTINCT C.CONTA CADASTRO,");
stbSelecao.AppendLine("C.NOME ASSOCIADO,");
stbSelecao.AppendLine("C.EMAIL,");
stbSelecao.AppendLine("C.TEL_CEL CELULAR,");
stbSelecao.AppendLine("COALESCE(C.CPF, C.CGC) CPF,");
stbSelecao.AppendLine("C.FISICA,");
stbSelecao.AppendLine("C.COD_AGENCIA,");
stbSelecao.AppendLine("C.ENDERECO || ' nr ' || C.END_NUM ENDERECO,");
stbSelecao.AppendLine("C.NACIONALIDADE,");
stbSelecao.AppendLine("C.CI AS RG,");
stbSelecao.AppendLine("CID.NOME || '-' || CID.UF CIDADE,");
stbSelecao.AppendLine("C.CEP,");
stbSelecao.AppendLine("H.NOME AS BAIRRO");
stbSelecao.AppendLine("FROM");
stbSelecao.AppendLine("FACMUTUO.C_CAD C");
stbSelecao.AppendLine("LEFT JOIN FACMUTUO.C_CIDADE CID ON C.COD_CID = CID.COD_CID");
stbSelecao.AppendLine("LEFT JOIN FACMUTUO.C_BAIRRO H ON C.COD_BAI = H.COD_BAI");
stbSelecao.AppendLine("ORDER BY");
stbSelecao.AppendLine("C.NOME");