SELECT
    A.CONTA,
    D.CONTAC,
    D.DT_ABERT DATA_ABERT_CC,
    CASE
        WHEN D.ATIVO = 3 AND D.CONTAC IS NOT NULL THEN D.DT_ENCER -- só puxa as datas de encerramento de contas encerradas, evitando erros presentes no BD
        ELSE NULL
    END AS DATA_ENCER_CC,
    CASE
        WHEN D.ATIVO = 3 THEN 'Encerrada'
        WHEN D.CONTAC IS NULL THEN NULL
        ELSE 'Ativa'
    END AS SITUACAO_CC,
    A.NOME AS ASSOCIADO,
    A.CPF || A.CGC AS CPF_CNPJ,
    CASE
        WHEN A.FISICA LIKE 'F' THEN 'Física'
        WHEN A.FISICA LIKE 'J' THEN 'Jurídica'
    END AS PESSOA,
    CASE
        WHEN A.SITUACAO LIKE 'Normal' THEN 'Ativo'
        WHEN A.SITUACAO LIKE 'Inativo' THEN 'Inativo'
        WHEN A.SITUACAO LIKE 'Demissionário' THEN 'Encerrado'
        ELSE A.SITUACAO
    END AS SITUACAO_CADASTRO,
    A.DATACAD AS DATA_ABERT_CADASTRO,
    A.DEMISSAO AS DATA_ENCER_CADASTRO,
    AG.COD_AGENCIA UNID,
    AG.NOME UNIDADE,
    B.APELIDO AGENTE,
    CASE
        WHEN A.EXECUCAO = 'T' THEN 'S'
        WHEN A.EXECUCAO = 'F' THEN 'N'
        ELSE NULL
    END AS EM_EXECUCAO,
    A.DT_EXECUCAO DATA_EXECUCAO,
    CASE
        WHEN A.TEL1 IN ('--', '(  )    -    ') THEN NULL
        ELSE A.TEL1
    END AS TELEFONE,
    CASE
        WHEN A.TEL_WHATSAPP IN ('--', '(  )     -    ') THEN NULL
        ELSE A.TEL_WHATSAPP
    END AS TELEFONE_WHATSAPP,
    A.EMAIL
FROM
    FACMUTUO.C_CAD A
    INNER JOIN CC_AGENCIA AG ON A.COD_AGENCIA = AG.COD_AGENCIA
    LEFT JOIN FACMUTUO.C_CAD B ON A.AGENTE = B.CONTA
    LEFT JOIN FACMUTUO.CC_CADASSOC C ON A.CONTA = C.CONTA
    LEFT JOIN CC_CAD D ON C.CONTAC = D.CONTAC
ORDER BY ASSOCIADO

