SELECT
    DISTINCT A.NOME ASSOCIADO,
    D.CONTAC,
    A.CONTA CADASTRO
FROM
    FACMUTUO.C_CAD A,
    FACMUTUO.CC_CADASSOC D,
    FACMUTUO.CC_CAD E
WHERE
    A.SITUACAO = 'Normal'
    AND A.CONTA = D.CONTA
    AND D.CONTAC = E.CONTAC
    AND E.ATIVO <> 3 -- 3 = encerrada