-----------------------------APENAS TITULARES-----------------------------
SELECT
    C.CONTA,
    CC.CONTAC
FROM
    FACMUTUO.C_CAD C
    LEFT JOIN FACMUTUO.CC_CADASSOC CC_A ON C.CONTA = CC_A.CONTA AND CC_A.TITULAR = 'T'
    LEFT JOIN FACMUTUO.CC_CAD CC ON CC_A.CONTAC = CC.CONTAC
    