SELECT
    C.CONTA,
    CC.CONTAC
FROM
    FACMUTUO.C_CAD C
    LEFT JOIN FACMUTUO.CC_CADASSOC CC_A ON C.CONTA = CC_A.CONTA
    LEFT JOIN FACMUTUO.CC_CAD CC ON CC_A.CONTAC = CC.CONTAC

-----------------------------APENAS TITULARES-----------------------------
 
SELECT
    C.CONTA,
    CC.CONTAC,
    CC_A.TITULAR
FROM
    FACMUTUO.C_CAD C
    LEFT JOIN FACMUTUO.CC_CADASSOC CC_A ON C.CONTA = CC_A.CONTA
    LEFT JOIN FACMUTUO.CC_CAD CC ON CC_A.CONTAC = CC.CONTAC
WHERE
    CC_A.TITULAR = 'T'