SELECT
    C.CONTA,
    PF2.COD_PERFIL,
    PF2.DESCRICAO
FROM
    FACMUTUO.C_CAD C
    LEFT JOIN C_CAD_PERFIL PF1 ON C.CONTA = PF1.CONTA
    LEFT JOIN C_PERFIL PF2 ON PF1.COD_PERFIL = PF2.COD_PERFIL
WHERE
    PF1.LOGIN <> 'MIGRACAO'