SELECT * FROM FACMUTUO.CC_AGENCIA D
SELECT * FROM SYS.COL WHERE CNAME LIKE '%COD_AGENCIA%'
SELECT * FROM SYS.COL WHERE CNAME LIKE 'CONTA%'
SELECT * FROM SYS.COL WHERE CNAME LIKE '%COD_CAIXA%'
SELECT * FROM SYS.COL WHERE CNAME LIKE '%COD_MOV%'

-- Pesquisar colunas de múltiplas tabelas
SELECT * FROM SYS.COL WHERE TNAME IN ('CX_REGISTRO', 'CX_MVOPEN', 'CX_CAIXAAB', 'CX_CAIXA') AND CNAME LIKE '%AGENCIA%'
SELECT * FROM CX_MVOPEN


-- Selecionar unidade
SELECT
    CASE
        WHEN D.NOME LIKE '%INDUSTRIAL%' THEN 'CASCAVEL'
        WHEN D.NOME LIKE '%CASCAVEL%' THEN 'CASCAVEL'
        ELSE D.NOME
    END UNIDADE
FROM
    FACMUTUO.CC_AGENCIA D



