SELECT
    CONTA,
    SUM(VLR_CONTABIL) AS VLR_CONTABIL
FROM (
    SELECT
        A.CONTA,
        ( A.SALDO + A.CTB_CORRECAO + A.CTB_JCAP + A.CTB_JNCAP + A.CTB_MORA + A.RAA_FUTURAS ) AS VLR_CONTABIL
    FROM
        FACMUTUO.E_SDA A, FACMUTUO.C_CAD B, FACMUTUO.C_CAD Z, FACMUTUO.C_CADUNI D, FACMUTUO.C_UNID C, FACMUTUO.E_TAXA E, FACMUTUO.E_LF F, FACMUTUO.E_CART G, FACMUTUO.C_CIDADE H, FACMUTUO.CC_AGENCIA AG, FACMUTUO.E_Forma_Bco J, FACMUTUO.C_SDA K, FACMUTUO.C_SETOR S, FACMUTUO.E_NIVEL NV
    WHERE
        A.CONTA = B.CONTA
        AND A.CONTA = K.CONTA
        AND A.ANOMES = K.ANOMES
        AND K.COD_AGENCIA = AG.COD_AGENCIA
        AND B.COD_UNID = D.COD_UNID
        AND B.CONTA = D.CONTA
        AND D.COD_UNID = C.COD_UNID
        AND B.AGENTE = Z.CONTA(+)
        AND D.COD_UNID = S.COD_UNID
        AND D.COD_SET = S.COD_SET
        AND A.COD_TAXA = E.COD_TAXA
        AND A.COD_LF = F.COD_LF
        AND A.COD_CART = G.COD_CART
        AND B.COD_CID = H.COD_CID
        AND A.COD_FORMA = J.COD_FORMA(+)
        AND A.NV_ATUAL = NV.NIVEL
        AND A.SALDO > 0
        AND A.COD_CART <> 10
        AND A.ANOMES = '2023/07'
) consultaVlrContabil
GROUP BY
    CONTA